config/routes.rb
TrainingPortal::Application.routes.draw do
  get "login" => "authentications#new", :as => "login"
  get "logout" => "authentications#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"
  get "register_to_dojo" => "sessions#register", :as => "register_to_dojo"
  get "unregister" => "sessions#unregister", :as => "unregister"
  root :to => "home#index"

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :sessions
  resources :home
  resources :users
  resources :authentications

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/session.rb
class Session < ActiveRecord::Base
  has_and_belongs_to_many :users
  
  accepts_nested_attributes_for :users, :allow_destroy => true
  
  def self.get_upcoming_open_session
    where(:status => "Open").order("date ASC").first
  end
end

app/models/training.rb
class Training < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :email, :enterprise_id, :password, :pass_confirmation
  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on =>:create
  validates_presence_of :enterprise_id
  validates_uniqueness_of :enterprise_id
  validates_presence_of :email

  has_and_belongs_to_many :sessions

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(enterprise_id, password)
    user = find_by_enterprise_id(enterprise_id)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def new
  end
  
  def create
    user = User.authenticate(params[:enterprise_id], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to "/home"#, :notice => "Logged in!"
    else
      flash.now.alert = "Invalid user or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/home"#, :notice => "Logged out!"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @open_session = Session.get_upcoming_open_session

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @open_session }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # GET /sessions
  # GET /sessions.json
  def index
    @sessions = Session.where(:status => "Closed")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sessions }
    end
  end

  # GET /sessions/1
  # GET /sessions/1.json
  def show
    @session = Session.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @session }
    end
  end

  def register
    if not session[:user_id]
      redirect_to login_path
      return
    end  
    
    open_session = Session.get_upcoming_open_session
      
    if not open_session
      redirect_to "/home"
      return
    end
    
    user = User.find_by_id(session[:user_id])
    open_session.users << user unless open_session.users.include? user

    redirect_to "/home", :notice => "Thank you for registering to the dojo! You will receive assistance confirmation based on the seats available."
  end
  
  def unregister
    open_session = Session.get_upcoming_open_session
    
    user_to_remove = User.find(params[:id])
    open_session.users.destroy(user_to_remove)
    
    open_session.save
    redirect_to "/admin"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to "/home"#, :notice => "Congratulations, you have signed up!"
    else
      render "new"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_user_registered?
    open_session = Session.get_upcoming_open_session
    
    if not (open_session || session[:user_id])
      return false
    end
    
    open_session.users.include? current_user
  end
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authentications/new.html.erb
<h1>Log in</h1>

<br />
<%= form_tag authentications_path do %>
  <p>
    <%= label_tag :enterprise_id %><br />
    <%= text_field_tag :enterprise_id, params[:enterprise_id] %>
  </p>
  <p>
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </p>
  <p>Not a user already? then <%= link_to "sign up!", signup_path %></p>
  <p><%= submit_tag "Log in" %></p>
<% end %>

app/views/home/index.html.erb
<% if @open_session %>
    <h1>next session</h1>

    <br />
    Date:
    <strong><%= @open_session.date.strftime("%A, %B %d %Y") %></strong>

    <br />
    Start time:
    <strong><%= @open_session.start_time.strftime("%H:%M") %></strong>

    <br />
    End time:
    <strong><%= @open_session.end_time.strftime("%H:%M") %></strong>

    <br />
    <br />
    <strong>Comments:</strong>
    <br />
    <%= @open_session.description %>

    <br />
    <br />
    <% if current_user_registered? %>
        You are already registered to the dojo. Will confirm assistance soon!!
    <% else %>
        <%= link_to "Register now!!", register_to_dojo_path %>
    <% end %>
<% else %>
    <h1>no open sessions yet, stay tuned!</h1>
<% end %>

<br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>atag coding dojos</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="header">
	<div id="menu">
		<ul>
			<li class="current_page_item"><a href="/home">home</a></li>
			<li><a href="/sessions">sessions</a></li>
			<li><a href="#">photos</a></li>
			<li class="last"><a href="#">about</a></li>
		</ul>
    </div>
</div>

<div id="user_nav">
    <% if current_user %>
        hello <%= current_user.enterprise_id %>!!
        (<%= link_to "log out", logout_path %>)
    <% else %>
        <%= link_to "sign up", signup_path %> or
        <%= link_to "log in", login_path %>
    <% end %>
</div>

<div id="logo">
	<h1>atag coding dojos </h1>
	<h2>because practice makes perfection...</h2>
</div>

<div id="banner"></div>

<div id="page">
    <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
    <% end %>

    <%= yield %>
</div>

<div id="footer">
	<p id="legal">(c) 2011. ATAG. All Rights Reserved. Developed with <strong>Rails</strong>, developed with <strong>passion :-)</strong></p>
</div>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up and become a student teacher in the next dojo</h1>

<br />
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :enterprise_id %>  (we ask for the Eid in order to easily reach out to you)<br />
    <%= f.text_field :enterprise_id %>
  </p>
  <p>
    <%= f.label :password %>  (even though it will be stored encrypted, we recommend not to use your real Eid password)<br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p><%= f.submit "Sign Up!" %></p>
<% end %>